### PR TITLE
Allow overriding default font

### PR DESCRIPTION
**Pull request by smurf0969**
Some small changes that allow changing the default font by setting a define.

### CODE REVIEW

**Comment by helmut64** [comment]
I created a branch of the OLED library and added a lot of enhancements including mbed-os support in addition to Arduino support. All enhancements should be backward compatible. As ThingPulse does not work on merges/enhancements for some time, I added your enhancement to my branch: https://github.com/helmut64/OLED_SSD1306/tree/mbed_os_support

I merged your pull request into my branch (mbed_os_support ) and hope that my branch gets adapted by ThingPulse, otherwise I continue with the OLED library on github account.

Merged pull request #238 to overwrite the default font.
I believe this is a very important feature because it is 
the memory requirement for a font never being used.
I do it a little bit difference, the init() functions allows an optional parameter with the default font,

**Comment by marcelstoer** [comment]
@helmut64 same comment from my side as with #247.

> I do it a little bit different, the init() functions allows an optional parameter with the default font

Why XOR instead of both? IMO it's useful to be able to set the default font on init _and_ through dedicated function. We could merge this one and then layer your addition on top of it in a follow-up PR, no?

**Comment by helmut64** [comment]
@marcelstoer at present the default font ArialMT_Plain_10 (2731 bytes in flash) is referenced and therfore eats this flash memory, even you you never use it. A dedicated function will not work because:
- The flash memory of the  ArialMT_Plain_10 is referenced and therefore is gets linked into the app, even if you set this later via a setDefaultFont() function after the constructor.
Keeping the fontData with a NULL pointer, it will crash if users don’t call  setDefaultFont().
Therefore my idea was to pass it as a default parameter in init().

PS: My friend from Arduino Hannover has use cases for Flipdot displays which works with the AVR therefore flash memory is limited. The Flipdot also uses optimized custom fonts (e.g. 8x7)

https://www.youtube.com/watch?time_continue=2&v=Qho6l2jwI9w

**Comment by marcelstoer** [comment]
I see your point. I didn't know that you're primarily concerned about memory consumption. 

> A dedicated function will not work

Well, it _will_ work but it comes at the cost of potentially wasting some memory as you correctly pointed out. In some setups this may be totally ok, in others it won't.

So, it'd be totally ok for me to drop this PR and accept a new one from you that implements the optional `init()` param.

**Comment by helmut64** [comment]
Sounds good and should work as well for smurf0969.

**Comment by marcelstoer** [comment]
>  a new one from you that implements the optional `init()` param.

Hadn't realized that this feature is already in your Mbed OS branch.

**Pull request closed without merging**
