### PR TITLE
ESP32 improve display speed for SSD1306

### PR DESCRIPTION
**Pull request by FREEWING-JP**
This PR is ESP32 improve display speed for SSD1306 .  
ESP32 can I2C Transfer Max 128 bytes .  
But This library Transfer Max 17 bytes .  
So I modded this .  

Tested with I2C SSD1306 OLED 128x64  
ESP32-D0WDQ6 (revision v1.0)  
ESP32-D0WD-V3 (revision v3.0)  
ESP32-S3 (revision v0.1)  
The drawing speed per screen has increased from 15.80ms to 12.02ms, which is 3.78ms(27% UP) faster !  

* Original Transfer 17 bytes (ESP32-D0WDQ6)  
image  
image  
  
* Modded Transfer 128 bytes (ESP32-D0WDQ6)  
image  
image

### CODE REVIEW

**Comment by marcelstoer** [comment]
Interesting observation. Thanks for the thorough testing 👍

**Comment by FREEWING-JP** [comment]
Thank You !

**Comment by thijstriemstra** [comment]
Would be great to have a new release so I can try this out.

**Comment by marcelstoer** [comment]
@thijstriemstra there were actually only 2: https://github.com/ThingPulse/esp8266-oled-ssd1306/compare/4.3.0...master Still, it's about time for another release.

**Comment by thijstriemstra** [comment]
Looking forward to a 27% performance gain!

**Pull request merged**
