### PR TITLE
OLEDDisplay.cpp -> fillCircle() fixed

### PR DESCRIPTION
**Pull request by NoobTracker**
Circles created with fillCircle() were one pixel taller than wide.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Great to see this PR, well done!

However, you moved the `.cpp` file out of `src/` into the root folder instead of editing the existing file. Please fix that in your `circles-fixed` branch and commit the change.

**Comment by NoobTracker** [comment]
Oh, sorry. I'll fix that.

**Comment by NoobTracker** [comment]
Okay, done.

**Comment by marcelstoer** [comment]
Check the "Files changed" tab: https://github.com/ThingPulse/esp8266-oled-ssd1306/pull/279/files

If you changed a single line then we would expect to see a single line in the diff.

**Comment by NoobTracker** [comment]
Ah, I've added a line (drawVerticalLine, line ~300)  and maybe removed an empty line.

**Comment by NoobTracker** [comment]
I don't now how GitHub handles that. I only changed fillCircle().

**Comment by NoobTracker** [comment]
Yes, it looks like that's the reason.

**Comment by NoobTracker** [comment]
Ooops, the actual reason is that I downloaded the files and replaced them on GitHub.

**Comment by marcelstoer** [comment]
You created a bit of a mess here because A) this one is "broken" as you realized and B) you were branching your other two branches off of _this one_ rather than `master`. Hence, we see _these_ commit in the other PRs, too.

Here's my proposal for a way forward:
- fix this PR by e.g.
  - `git checkout circles-fixed`
  - `git reset --hard origin/master` // you will loose all local changes!
  - change that one(?) line that needs fixing
  - `git commit -am "whatever message"`
  - `git push --force`
- then EITHER wait for this PR to land and proceed likewise for the other branches
- OR proceed with the other branches right now and deal with potential merge conflicts later

**Comment by NoobTracker** [comment]
The problem with this is that the newer version with the ring functions all changes the circular functions. In addition, the header file must also change. When I try to do this on GitHub, it is much harder to test the program. I would have to download it then. And the latest version (keywords) contains all changes to circles-fixed and circles-improved-rings. And where can I use this command line?

**Pull request closed without merging**
