### PR TITLE
Standalone html page to graphically edit fonts

### PR DESCRIPTION
**Pull request by reivaxy**
This page needs no server, can be opened straight from your disk and allows for designing new fonts and generate the code to use them with this library, or editing existing ones copy/pasting their char array, and generating the new one.

### CODE REVIEW

**Comment by reivaxy** [comment]
Hi @lorol, thanks for reporting this bug. It's now fixed.

**Comment by lorol** [comment]
Hi again @reivaxy 
One of my Mozila's :) displays your navigation arrows `..."left">ðŸ¡¨</th>...` as unknown character' rectangles.  I did replace in code by [html arrows](https://www.toptal.com/designers/htmlarrows/) symbols, example `..."left">&larr;</th>...` and now all is good.  These html entities look more universal. What do you think?

**Comment by reivaxy** [comment]
Hi again @lorol 
Is it on mobile ? I don't have the issue with Firefox on w10.
I thought unicode10 would be good enough :)
But of course, all right, I'll change that. 
I guess there is no html entity for the "copy" icon 🗐 ? I intend to implement copying pixels from one char to another. I guess I'll just have to use a data: schema with an img tag

**Comment by lorol** [comment]
:) you can always improvise with something like: `&wedgeq;   &veeeq;`  :  &wedgeq;   &veeeq;

# ≙  (Copy)
# ≚  (Paste)

**Comment by lorol** [comment]
Hi @reivaxy,

[Here](https://github.com/squix78/esp8266-oled-ssd1306/files/1413284/glyphEditor_lorol_test.zip) is my variant after playing around. 
I added "load from file" and after you generate, "output to file" functionality.
Feel free to use any idea of it if you like. 
Tested on Mozilla Firefox (win64) browser.
Still some stuff to be improved and debugged.

**Comment by reivaxy** [comment]
Hi @lorol 
Nice addition but I'd rather you submit a PR ;)

**Comment by lorol** [comment]
Hi @reivaxy,
I forked earlier the same rep from squix and did some additions for my purpose, I believe they are compatible. Now I added your glyphEditor.html to my fork and will commit my changes over.
But I am not sure how pull requests and branching work in this scenario. Can you help me?
I think I tried to create a pull request this morning but I don't see it anywhere ...

**Comment by reivaxy** [comment]
Hi @lorol 

I did see it, you would see it clicking on the "Pull Request" link in black header very top of this page.
I think you need to fork my repo to submit the modified file, so that the diff works fine.

**Comment by reivaxy** [comment]
@squix78 is this repo discontinued ? thanks

**Comment by reivaxy** [comment]
Can someone merge this ? Thanks.

**Comment by squix78** [comment]
This is really cool! Thank you so much and sorry that it took so long to be integrated!

**Comment by reivaxy** [comment]
Thanks! And I'm the one to thank you for your very helpful libraries!

**Pull request merged**
