### PR TITLE
Support for additional display types

### PR DESCRIPTION
**Pull request by bratoff**
OLEDDisplay.h has been modified so that all hardware-dependent functions are virtual.  Nonstandard geometry is supported using existing GEOMETRY_RAWMODE.

New files:
PCD8544Spi.h - implements Nokia 5110 display using SPI
WeatherStationDemoWiFiManager.ino
WeatherStationFonts.h
WeatherStationImages.h - these 3 files, taken from the WeatherStation library, have been modified to support PCD8544Spi in addition to the original OLED display types.

None of the new files are required, except as examples of new functionality.

### CODE REVIEW

**Comment by marcelstoer** [comment]
Just happened to see the close-notification fly by in my email inbox. Don't know why I didn't notice it when the stale bot flagged this a week ago.

I am sorry his project hasn't received the attention it actually deserves lately.

**Comment by bratoff** [comment]
> Just happened to see the close-notification fly by in my email inbox. Don't know why I didn't notice it when the stale bot flagged this a week ago.
> 
> I am sorry his project hasn't received the attention it actually deserves lately.

No worries.  I know you're working on another library that could supersede this one for more modern displays, but I do still find this library very useful so I appreciate your response.

**Comment by marcelstoer** [comment]
I just went through your commits again. Not sure what really happened but it looks like a Git rebase gone wrong. Am I correct in assuming that what you really wanted to contribute is in 8faf980?

**Comment by bratoff** [comment]
> I just went through your commits again. Not sure what really happened but it looks like a Git rebase gone wrong. Am I correct in assuming that what you really wanted to contribute is in [8faf980](https://github.com/ThingPulse/esp8266-oled-ssd1306/commit/8faf980431bee92ffd9ae5c78ca31b5594faaaaf)?

I'm afraid my github skills are not all they should be, so yes, my rebase attempt appears to have gone horribly wrong.

My contribution includes all of the following:  cdfdbfe, cba4b00, 21b2217, and 8faf980
The intent is to virtualize all hardware-dependent functions in OLEDDisplay.h and then add two new display types that depend on the updated parent class:  KS0108SR.h and PCD8544Spi.h

I did also make a lot of changes to WeatherStationDemoWiFiManager.ino, but since that is just a demo I'm fine if you don't accept them.

I do not think any of the other changes that have occurred in your main branch will break any of my changes.

My apologies again for any chaos I may have inadvertently caused.

**Pull request closed without merging**
