### PR TITLE
Support Mega2560 board (and other 8-bit boards)

### LINKED ISSUE #403: Small tweaks allows running on ATMega2560
**Describe the bug**
The library does not compile out of the box for an Arduino ATMega2560 board (or any other 8-bit board)

**To Reproduce**
1. Open Sketch
2. Set Board to and Arduino Mega2560
3. Compile
4. `_frequency` overflow

**Expected behavior**
Would be great to be able to use this library on a Arduino 8-bit board (almost there)

**Versions (please complete the following information):**
 - Library: 4.4.1
 - Platform: Arduino atmelavr@4.2.0

**Additional context**
If the type of the `_frequency` variable of the `SSD1306Wire` class is changed from `int` to `long`, it will work.
Also, using PlatformIO, I get compiler warnings about ctor parameters shadowing members. If you remove the leading underscores from the ctor parameters, it goes away.

### PR DESCRIPTION
**Pull request by ClutchplateDude**
Change `frequency` to `long`

Resolves #403

### CODE REVIEW

**Review by marcelstoer — CHANGES_REQUESTED** [review]
I am personally not a fan of these `_` parameter name prefixes either. I understand the compiler warnings but for consistency reasons one cannot change this only here.

**Comment by ClutchplateDude** [comment]
What do you suggest? Change them all? We compile with warnings as errors so it was a blocker for us which is why we have forked it for now. But would like to use the official repo when possible.

**Comment by marcelstoer** [comment]
> What do you suggest?

Not sure...not being too familiar with the early history of this lib makes this a difficult question for me. As changing the constructor parameters is the less invasive of the two options, I guess I would prefer that.

Also, while analyzing I realized the `_` prefix wasn't applied consistently anyway. The geometry parameter (`OLEDDISPLAY_GEOMETRY`) is always just called `g` rather than `_g`.

**Comment by ClutchplateDude** [comment]
Yeah, there's often a tradeoff of readability/maintainability vs. backwards compatibility, or not making breaking changes. But I think internals should be open to change, since they should not be used by consumers. 
As far as coding standards go, in my C++ experience, using underscores is usually reserved for class members and function parameters get normal arguments. But that's like arguing about spaces vs. tabs.... you'll always find at least one of each side in any group :-)

**Comment by ClutchplateDude** [comment]
Looking at all the source, It's pretty inconsistent:
- all the hardware-related files (`SSD1306*` and `SH1106*`) use the `_` prefix for members. Function arguments do not have a leading `_` **except** for ctor args
- all the `OLED*` files use `camelCased` member and argument names for **all** functions and ctors

I would convert all ctors in the `SSD*` and `SH*` files to use `camelCased` arguments. I can do that in this PR if desired.

**Comment by marcelstoer** [comment]
> I can do that in this PR if desired.

That'd be much appreciated, thanks.

**Pull request merged**
