### PR TITLE
Fixed and improved circles + keywords

### PR DESCRIPTION
**Pull request by NoobTracker**
This version contains all the improvements of the other three versions: Improved circles, even more improved circles and rings and keywords.

### CODE REVIEW

**Comment by NoobTracker** [comment]
Is there anything wrong with this version?

**Comment by marcelstoer** [comment]
The same issue(s) as with your previous PRs: https://github.com/ThingPulse/esp8266-oled-ssd1306/pull/284/files. As far as Git is concerned you replaced the entire `OLEDDisplay.h` and `.cpp`.

**Comment by NoobTracker** [comment]
Yes, but it will be very difficult to find the lines affected and then replace them. I could try, but reluctant.

**Comment by NoobTracker** [comment]
Can you reject this pull request so that I can create a new version? I don't know how to delete your own forked version ...

**Pull request closed without merging**
