### PR TITLE
correct type to avoid compiler warning

### PR DESCRIPTION
**Pull request by 0xPIT**
`warning: narrowing conversion of '128' from 'int' to 'const char' inside { } [-Wnarrowing]`

### CODE REVIEW

**Comment by FWeinb** [comment]
Thanks for taking the time and fixing these issues. Could you please update the type declaration in the missing spots too? 

You need to fix it in `SSD1306ClockDemo.ino`.

We can't merge it right away because this will cause an API change and according to semver this will need a major version change.

**Comment by 0xPIT** [comment]
I'm on it :) 
(new to platform.io)

**Comment by 0xPIT** [comment]
Ok, seems to work now, I have some issues with pio, obviously from remains of an early version. need to clean and reinstall.

anyways: I propose to change the type to `uint8_t` for image and font data. (it should be unsigned anyways due to values >127 in image and font data and the linter in atom complaining)

**Comment by FWeinb** [comment]
You are correct in proposing to change to `uint8_t` I put this on the `4.0.0` milestone because otherwise we would break semver so this change has to wait a little.

**Pull request merged**
