### PR TITLE
Fix for nonESP32 with one HW I2C

### PR DESCRIPTION
**Pull request by benoitm974**
Please note this is blind change as I don't have a non ESP32 arduino to test

### CODE REVIEW

**Comment by benoitm974** [comment]
Thanks for the feedback ! glad it worked.

**Comment by marcelstoer** [comment]
I confirmed this fixes the issue. As you're at it please properly format the fragment as below (note the spaces)

```c
#if !defined(ARDUINO_ARCH_ESP32)
      this->_wire = &Wire;
#else
      this->_wire = (_i2cBus == I2C_ONE) ? &Wire : &Wire1;
#endif
```

**Comment by benoitm974** [comment]
> I confirmed this fixes the issue. As you're at it please properly format the fragment as below (note the spaces)
> 
> ```c
> #if !defined(ARDUINO_ARCH_ESP32)
>       this->_wire = &Wire;
> #else
>       this->_wire = (_i2cBus == I2C_ONE) ? &Wire : &Wire1;
> #endif
> ```

Done.

**Comment by millenseer** [comment]
Thanks for your continuous and amazing work!

**Comment by thijstriemstra** [comment]
can someone put out a new release please? cc @marcelstoer

**Comment by marcelstoer** [comment]
I'm reluctant to cut a release without #296 being addressed. It appears to be a regression but I currently don't have a clue.

**Comment by thijstriemstra** [comment]
A platformio build on multiple boards would help, and I see there's a .travis.yml file present but the build is not triggered on travis somehow, there are no 'green ticks' behind the commits indicating it ran a travis build. Can you verify/look into this @marcelstoer? Make sure this repository has travis enabled?

**Comment by marcelstoer** [comment]
I know it looked into this the other day.

Travis CI is enabled and it does run for all commits (and PRs). The build badge at the top of the README at https://github.com/ThingPulse/esp8266-oled-ssd1306 is real. However, for whatever reason GitHub only _triggers_ the builds, I verified this, but fails to pull in status information about those builds. I've seen this with some other projects I maintain and I even contacted GitHub support about this issue. They never replied but over there the feature came back after a while out of nowhere.

**Comment by thijstriemstra** [comment]
Ah I missed the badge. I'll open a pull request that tests against other boards. In theory, #296 should be caught by adding the correct device and a test case.

**Comment by thijstriemstra** [comment]
>  I'll open a pull request that tests against other boards. 

See #300

**Pull request merged**
